apiVersion: v1
kind: Service
metadata:
  name: session-essence-site
  namespace: zaphod
  labels:
    app: session-essence-site
spec:
  selector:
    app: session-essence-site
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
